const stockProductos =
[
          {
                    id: 1,
                    estacion: 'Verano',
                    nombre: 'Remera',
                    detalle: 'Remera manga corta',
                    desc: 'Outfits con mucha onda',
                    precio: 2500,
                    img: './public/img/remera.jpg',
                    imgLogo: './public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 2,
                    estacion: 'Verano',
                    nombre: 'Musculosa',
                    detalle: 'Musculosa urbana/surf',
                    desc: 'Cómodas y cancheras',
                    precio: 2000,
                    img: './public/img/musculosa.jpg',
                    imgLogo: './public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 3,
                    estacion: 'Verano',
                    nombre: 'Bermuda',
                    detalle: 'Bermuda camuflada',
                    desc: 'Combinan cualquier estilo',
                    precio: 4400,
                    img: './public/img/bermuda.jpg',
                    imgLogo: './public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 4,
                    estacion: 'Invierno',
                    nombre: 'Campera de abrigo',
                    detalle: 'Campera de abrigo con doble polar, capucha y bolsillo interno',
                    desc: 'Olvidate de pasar frío',
                    precio: 15000,
                    img: './public/img/camperaDeAbrigo.jpg',
                    imgLogo: './public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 5,
                    estacion: 'Invierno',
                    nombre: 'Buzo de polar',
                    detalle: 'El mejor polar para estación otoño/invierno',
                    desc: 'El polar más fachero',
                    precio: 8000,
                    img: './public/img/buzoDePolar.jpg',
                    imgLogo: './public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 6,
                    estacion: 'Invierno',
                    nombre: 'Jogging de frisa',
                    detalle: 'Los más cómodos de nuestra marca',
                    desc: 'Pantalón para tu día a día',
                    precio: 5500,
                    img: './public/img/joggingDeFrisa.jpg',
                    imgLogo: './public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
]