const stockProductos =
[
          {
                    id: 1,
                    estacion: 'Verano',
                    nombre: 'Remera',
                    desc: 'Outfits clásico urbano',
                    precio: 2500,
                    img: 'public/img/remera.jpg',
                    imgLogo: 'public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 2,
                    estacion: 'Verano',
                    nombre: 'Musculosa',
                    desc: 'Cancheras estilo urbana/surf',
                    precio: 2000,
                    img: 'public/img/musculosa.jpg',
                    imgLogo: 'public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 3,
                    estacion: 'Verano',
                    nombre: 'Bermuda',
                    desc: 'Estilo camuflado combinan cualquier estilo',
                    precio: 4400,
                    img: 'public/img/bermuda.jpg',
                    imgLogo: 'public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 4,
                    estacion: 'Invierno',
                    nombre: 'Campera de abrigo',
                    desc: 'Doble polar, capucha y bolsillo interno',
                    precio: 15000,
                    img: 'public/img/camperaDeAbrigo.jpg',
                    imgLogo: 'public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 5,
                    estacion: 'Invierno',
                    nombre: 'Buzo de polar',
                    desc: 'Ideal para estación otoño/invierno',
                    precio: 8000,
                    img: 'public/img/buzoDePolar.jpg',
                    imgLogo: 'public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
          {
                    id: 6,
                    estacion: 'Invierno',
                    nombre: 'Jogging de frisa',
                    desc: 'Pantalón cómodo para tu día a día',
                    precio: 5500,
                    img: 'public/img/joggingDeFrisa.jpg',
                    imgLogo: 'public/img/guilbas logo.png',
                    slogan: 'Guilbas Urban Wear',
                    cantidad: 1,
          },
]